import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {"id":"1","name":"Veg Manchow Soup","price":"₹89","category":"Soup"},
  {"id":"2","name":"Veg Hot N Sour Soup","price":"₹89","category":"Soup"},
  {"id":"3","name":"Tomato Soup","price":"₹119","category":"Soup"},
  {"id":"4","name":"Cream of Mushroom Soup","price":"₹119","category":"Soup"},
  {"id":"5","name":"House Fries","price":"₹109","category":"Munchies & Starters"},
  {"id":"6","name":"Masala Papad","price":"₹79","category":"Munchies & Starters"},
  {"id":"7","name":"Peri Peri French Fries","price":"₹129","category":"Munchies & Starters"},
  {"id":"8","name":"Nachos","price":"₹109","category":"Munchies & Starters"},
  {"id":"9","name":"Potato Veggies","price":"₹129","category":"Munchies & Starters"},
  {"id":"10","name":"Cheese Nachos","price":"₹129","category":"Munchies & Starters"},
  {"id":"11","name":"Cheese Corn Triangles","price":"₹149","category":"Munchies & Starters"},
  {"id":"12","name":"Loded Nachos","price":"₹149","category":"Munchies & Starters"},
  {"id":"13","name":"Veg Fingers","price":"₹129","category":"Munchies & Starters"},
  {"id":"14","name":"Cheese Cigar Rolls","price":"₹149","category":"Munchies & Starters"},
  {"id":"15","name":"Paneer Fingers","price":"₹179","category":"Munchies & Starters"},
  {"id":"16","name":"Jalapeno Poppers","price":"₹129","category":"Munchies & Starters"},
  {"id":"17","name":"Smiles Crispy Potato","price":"₹149","category":"Munchies & Starters"},
  {"id":"18","name":"Cheese Balls","price":"₹199","category":"Munchies & Starters"},
  {"id":"19","name":"Potato Bites","price":"₹129","category":"Munchies & Starters"},
  {"id":"20","name":"Dahi Ke Sholay","price":"₹149","category":"Munchies & Starters"},
  {"id":"21","name":"Veg Nuggets","price":"₹169","category":"Munchies & Starters"},
  {"id":"22","name":"Peanut Masala","price":"₹109","category":"Munchies & Starters"},
  {"id":"23","name":"Plain Maggi","price":"₹69","category":"Maggi"},
  {"id":"24","name":"Vegetable Maggi","price":"₹99","category":"Maggi"},
  {"id":"25","name":"Cheese Maggi","price":"₹109","category":"Maggi"},
  {"id":"26","name":"Punjabi Tadka Maggi","price":"₹119","category":"Maggi"},
  {"id":"27","name":"Vegetable Cheese Maggi","price":"₹119","category":"Maggi"},
  {"id":"28","name":"Egg Vegetable Maggi","price":"₹119","category":"Maggi"},
  {"id":"29","name":"Boild Egg","price":"₹35","category":"Salads"},
  {"id":"30","name":"Green Salad","price":"₹129","category":"Salads"},
  {"id":"31","name":"Greek Salad","price":"₹149","category":"Salads"},
  {"id":"32","name":"Cesar Salad","price":"₹159","category":"Salads"},
  {"id":"33","name":"Choice of Ice Cream","price":"₹99","category":"Dessert"},
  {"id":"34","name":"Browni with Ice Cream","price":"₹129","category":"Dessert"},
  {"id":"35","name":"Hot Gulab Jamun","price":"₹99","category":"Dessert"},
  {"id":"36","name":"Veg Noodles","price":"₹159","category":"China Town"},
  {"id":"37","name":"Veg Fried Rice","price":"₹189","category":"China Town"},
  {"id":"38","name":"Veg Hakka Noodles","price":"₹169","category":"China Town"},
  {"id":"39","name":"Paneer Fried Rice","price":"₹219","category":"China Town"},
  {"id":"40","name":"Chilli Garlic Noodles","price":"₹199","category":"China Town"},
  {"id":"41","name":"Egg Fried Rice","price":"₹199","category":"China Town"},
  {"id":"42","name":"Paneer Wrap","price":"₹99","category":"Roll Station"},
  {"id":"43","name":"Honey Chilli Potato","price":"₹169","category":"Roll Station"},
  {"id":"44","name":"Egg Roll","price":"₹99","category":"Roll Station"},
  {"id":"45","name":"Crispy Corn (Salt N Papper)","price":"₹169","category":"Roll Station"},
  {"id":"46","name":"Paneer Kathi Roll","price":"₹149","category":"Roll Station"},
  {"id":"47","name":"Chilly Paneer","price":"₹219","category":"Roll Station"},
  {"id":"48","name":"Veg Spring Roll","price":"₹149","category":"Roll Station"},
  {"id":"49","name":"Veg Manchurian","price":"₹219","category":"Roll Station"},
  {"id":"50","name":"Crunchy Spring Roll","price":"₹189","category":"Roll Station"},
  {"id":"51","name":"Mushroom Chilly","price":"₹299","category":"Roll Station"},
  {"id":"52","name":"Steam Momos","price":"₹99","category":"Momo Junction"},
  {"id":"53","name":"Fried Momos","price":"₹109","category":"Momo Junction"},
  {"id":"54","name":"Paneer Momos","price":"₹149","category":"Momo Junction"},
  {"id":"55","name":"Crunchy Momos","price":"₹159","category":"Momo Junction"},
  {"id":"56","name":"Veg Pizza Pocket","price":"₹169","category":"Pizzeria"},
  {"id":"57","name":"Margherita Pizza","price":"₹219","category":"Pizzeria"},
  {"id":"58","name":"Mexican Wave Pizza","price":"₹259","category":"Pizzeria"},
  {"id":"59","name":"Vatican Delight Pizza","price":"₹279","category":"Pizzeria"},
  {"id":"60","name":"OTC Pizza","price":"₹259","category":"Pizzeria"},
  {"id":"61","name":"Mushroomian Pizza","price":"₹299","category":"Pizzeria"},
  {"id":"62","name":"Paneer Barbeque Pizza","price":"₹339","category":"Pizzeria"},
  {"id":"63","name":"Bean's Taco","price":"₹169","category":"Mexican"},
  {"id":"64","name":"Canjun Paneer","price":"₹169","category":"Mexican"},
  {"id":"65","name":"Burito Bowl","price":"₹289","category":"Mexican"},
  {"id":"66","name":"Crispy Aloo Tikki Burger","price":"₹119","category":"Burger"},
  {"id":"67","name":"Crunchy King Burger","price":"₹199","category":"Burger"},
  {"id":"68","name":"Garlic Bread","price":"₹129","category":"Bread"},
  {"id":"69","name":"Cheese Garlic Bread","price":"₹159","category":"Bread"},
  {"id":"70","name":"Bruschetta Bread","price":"₹169","category":"Bread"},
  {"id":"71","name":"OTC Garlic Bread","price":"₹179","category":"Bread"},
  {"id":"72","name":"Classic Book Maker","price":"₹99","category":"Sandwich"},
  {"id":"73","name":"Egg Sandwich","price":"₹119","category":"Sandwich"},
  {"id":"74","name":"Bang Bang Sandwich","price":"₹119","category":"Sandwich"},
  {"id":"75","name":"Paneer Tikka Sandwich","price":"₹149","category":"Sandwich"},
  {"id":"76","name":"Pizza Baked Sandwich","price":"₹179","category":"Sandwich"},
  {"id":"77","name":"Pasta (Penne - Arabita/Alfredo/Rosatella)","price":"₹199","category":"Pasta"},
  {"id":"78","name":"Chai","price":"₹29","category":"Hot Beverages"},
  {"id":"79","name":"Hot Coffee","price":"₹49","category":"Hot Beverages"},
  {"id":"80","name":"Green Tea","price":"₹59","category":"Hot Beverages"},
  {"id":"81","name":"Black Coffee","price":"₹59","category":"Hot Beverages"},
  {"id":"82","name":"Hot Chocolate","price":"₹99","category":"Hot Beverages"},
  {"id":"83","name":"Cold Coffee (S)","price":"₹59","category":"Cold Beverages"},
  {"id":"84","name":"Cold Coffee (L)","price":"₹99","category":"Cold Beverages"},
  {"id":"85","name":"Cold Coffee With Ice Cream","price":"₹129","category":"Cold Beverages"},
  {"id":"86","name":"Hazelnut Cold Coffee","price":"₹149","category":"Cold Beverages"},
  {"id":"87","name":"Strawberry Frappe","price":"₹139","category":"Frappe & Shakes"},
  {"id":"88","name":"Black Current Frappe","price":"₹139","category":"Frappe & Shakes"},
  {"id":"89","name":"Blueberry Frappe","price":"₹139","category":"Frappe & Shakes"},
  {"id":"90","name":"Pineapple Frappe","price":"₹139","category":"Frappe & Shakes"},
  {"id":"91","name":"Oreo Frappe","price":"₹139","category":"Frappe & Shakes"},
  {"id":"92","name":"Kitkat Frappe","price":"₹139","category":"Frappe & Shakes"},
  {"id":"93","name":"Mango Shake","price":"₹139","category":"Frappe & Shakes"},
  {"id":"94","name":"Choco Frappe","price":"₹139","category":"Frappe & Shakes"},
  {"id":"95","name":"Butter Scotch Shake","price":"₹139","category":"Frappe & Shakes"},
  {"id":"96","name":"Lotus Biscoff Shake","price":"₹179","category":"Frappe & Shakes"},
  {"id":"97","name":"Lemonade","price":"₹89","category":"Coolers & Iced Tea"},
  {"id":"98","name":"Masala Lemonade","price":"₹99","category":"Coolers & Iced Tea"},
  {"id":"99","name":"Kala Khatta","price":"₹109","category":"Coolers & Iced Tea"},
  {"id":"100","name":"Blue Lagoon","price":"₹109","category":"Coolers & Iced Tea"},
  {"id":"101","name":"Virgin Mojito","price":"₹109","category":"Coolers & Iced Tea"},
  {"id":"102","name":"Lemon Ice Tea","price":"₹109","category":"Coolers & Iced Tea"},
  {"id":"103","name":"Watermelon Ice Tea","price":"₹129","category":"Coolers & Iced Tea"},
  {"id":"104","name":"Green Apple Mojito","price":"₹129","category":"Coolers & Iced Tea"},
  {"id":"105","name":"Red Bull Icetea","price":"₹219","category":"Coolers & Iced Tea"},
];
    
